- name: Create Jenkins Jobs
  hosts: all
  tasks:
    - name: Create Jenkins Jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.yml') }}"
        name: test-create-from-ansible
        password: admin123
        url: http://172.31.80.96:8080
        user: admin

